/**
 @idea : just add for every elements his correspond value in instrument b ,,x= StringA[currow]+idxvalue+d;
         then sort dsc ,,, cause he want highest indeces work get the highest priority 
         and try to find the suitable row in col[i...n] that less than curx and curx <= col[i]+35 
         if no one valid put 'x' in all rows in this column if valid put '-' if the index not used :) 


         Happy Solving :)
**/


#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <string>
#include <string.h>
using namespace std;


const int N = 55;
int col[N];
vector<int>notes[N];

class StringsAndTabs {
public:

	vector <string> transformTab(vector <string> tab, vector <int> sa, vector <int>sb, int d) {
		string pos = "0123456789";
		memset(notes, 0, sizeof(notes));
		int n = sb.size();
		for (char i = 'A'; i <= 'Z'; i++) {
			pos += i;
		}
		for (int i = 0; i<(int)tab[0].size(); i++) {
			for (int j = 0; j<(int)tab.size(); j++) {
				if (tab[j][i] != '-')notes[i].push_back(sa[j] + (int)pos.find(tab[j][i]) + d);
			}
			sort(notes[i].begin(), notes[i].end());
			reverse(notes[i].begin(), notes[i].end());
		}
		vector<string>ans(n);
		for (int i = 0; i<tab[0].size(); i++) {
			memset(col, -1, sizeof(col));
			bool f = 1;
			for (int j = 0; j<(int)notes[i].size(); j++) {
				int x = notes[i][j];
				int tmp = -1;
				for (int k = 0; k<n; k++) {
					if (col[k] == -1 && x >= sb[k] && x <= sb[k] + 35) {
						if (tmp == -1 || sb[k] >= sb[tmp])tmp = k;
					}
				}
				if (tmp == -1) { f = 0; break; }
				col[tmp] = x - sb[tmp];
			}
			if (!f) {
				for (int k = 0; k<n; k++) {
					ans[k] += 'x';
				}
			}
			else {
				for (int k = 0; k<n; k++) {
					if (col[k] == -1)ans[k] += '-';
					else ans[k] += pos[col[k]];
				}
			}

		}

		return ans;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, vector <int> p1, vector <int> p2, int p3, bool hasAnswer, vector <string> p4) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p2.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p2[i];
	}
	cout << "}" << "," << p3;
	cout << "]" << endl;
	StringsAndTabs *obj;
	vector <string> answer;
	obj = new StringsAndTabs();
	clock_t startTime = clock();
	answer = obj->transformTab(p0, p1, p2, p3);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "{";
		for (int i = 0; int(p4.size()) > i; ++i) {
			if (i > 0) {
				cout << ",";
			}
			cout << "\"" << p4[i] << "\"";
		}
		cout << "}" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "{";
	for (int i = 0; int(answer.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << answer[i] << "\"";
	}
	cout << "}" << endl;
	if (hasAnswer) {
		if (answer.size() != p4.size()) {
			res = false;
		}
		else {
			for (int i = 0; int(answer.size()) > i; ++i) {
				if (answer[i] != p4[i]) {
					res = false;
				}
			}
		}
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	}
	else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	}
	else if (hasAnswer) {
		cout << "Match :-)" << endl;
	}
	else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	vector <string> p0;
	vector <int> p1;
	vector <int> p2;
	int p3;
	vector <string> p4;

	{
		// ----- test 0 -----
		string t0[] = { "-----------------","-------------0-1-","---------0-2-----","---0-2-3---------","-3---------------","-----------------" };
		p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
		int t1[] = { 28,23,19,14,9,4 };
		p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
		int t2[] = { 9 };
		p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
		p3 = 0;
		string t4[] = { "-3-5-7-8-A-C-E-F-" };
		p4.assign(t4, t4 + sizeof(t4) / sizeof(t4[0]));
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
	}

	{
		// ----- test 1 -----
		string t0[] = { "-4457754-20024422-4457754-20024200-" };
		p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
		int t1[] = { 0 };
		p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
		int t2[] = { 28,23,19,14,9,4 };
		p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
		p3 = 12;
		string t4[] = { "-----------------------------------","-----------------------------------","----00---------------00------------","-223--32-0--02200-223--32-0--020---","----------33---------------33---33-","-----------------------------------" };
		p4.assign(t4, t4 + sizeof(t4) / sizeof(t4[0]));
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
	}

	{
		// ----- test 2 -----
		string t0[] = { "-----------------------------------","-----------------------------------","----00---------------00------------","-223--32-0--02200-223--32-0--020---","----------33---------------33---33-","-----------------------------------" };
		p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
		int t1[] = { 28,23,19,14,9,4 };
		p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
		int t2[] = { 33,28,24,31 };
		p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
		p3 = 12;
		string t4[] = { "-----------------------------------","-001--10-----00---001--10-----0----","---------2002--22---------2002-200-","----00---------------00------------" };
		p4.assign(t4, t4 + sizeof(t4) / sizeof(t4[0]));
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
	}

	{
		// ----- test 3 -----
		string t0[] = { "-----0------2-2222--0-------0-","----0------2---222---5-----55-","---0------2-----22----9---999-","--0------2-------2-----E-EEEE-","-0------2---------------------","0------2----------------------" };
		p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
		int t1[] = { 28,23,19,14,9,4 };
		p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
		int t2[] = { 33,28,28 };
		p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
		p3 = 12;
		string t4[] = { "xxx-27-xx-049-999x--7777-777x-","xxx----xx-------5x---------Cx-","xxx3---xx0-----99x--------CCx-" };
		p4.assign(t4, t4 + sizeof(t4) / sizeof(t4[0]));
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
	}

	{
		// ----- test 4 -----
		string t0[] = { "012345---------","---------UVWXYZ" };
		p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
		int t1[] = { -2,2 };
		p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
		int t2[] = { 0 };
		p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
		p3 = 0;
		string t4[] = { "xx0123---WXYZxx" };
		p4.assign(t4, t4 + sizeof(t4) / sizeof(t4[0]));
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
	}

	{
		// ----- test 5 -----
		string t0[] = { "0220----02--","75--75----57","------B9B9B9","--242424----" };
		p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
		int t1[] = { 33,28,24,31 };
		p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
		int t2[] = { 33,28,28 };
		p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
		p3 = 0;
		string t4[] = { "222222222222","------------","555555555555" };
		p4.assign(t4, t4 + sizeof(t4) / sizeof(t4[0]));
		all_right = KawigiEdit_RunTest(5, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	}
	else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
