#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <string.h>
#include <string>

using namespace std;


const int N=27;
int Change[N][N],Final[N][N];
int  dp[55][55];
string s;

class PalindromizationDiv1 {
public:
        int solve(int i,int j){
           if(i>=j)return 0;
           int &ret=dp[i][j];
           if(ret!=-1)return ret;
           ret=(int)1e9;
          
           ret=min(ret,solve(i+1,j-1)+Final[s[i]-'a'][s[j]-'a']);
           ret=min(ret,solve(i+1,j)+Final[26][s[i]-'a']);
           ret=min(ret,solve(i,j-1)+Final[26][s[j]-'a']);
           return ret;
        }
        void modify(const vector<string>&v){
             for(int i=0;i<(int)v.size();i++){
                 istringstream in(v[i]);
                 string str;
                 char a,b;
                 int cost;
                 in>>str>>a;
                 if(str=="add"){
                   in>>cost;
                   Change[26][a-'a']=cost;
                 }else if(str=="erase"){
                   in>>cost;
                   Change[a-'a'][26]=cost;
                 }else{
                   in>>b>>cost;
                   Change[a-'a'][b-'a']=cost;
                 }
             }
        }

      	int getMinimumCost(string word, vector <string> op) {
      	     s=word;
      	     memset(dp,-1,sizeof(dp));
      	     for(int i=0;i<N;i++){
      	         for(int j=0;j<N;j++){
      	            if(i==j)Change[i][j]=0;
      	            else Change[i][j]=(int)1e9;
      	         }
      	     }
      	     modify(op);
      	     for(int k=0;k<N;k++){
      	       for(int i=0;i<N;i++){
      	         for(int j=0;j<N;j++){
      	            Change[i][j]=min(Change[i][j],Change[i][k]+Change[k][j]);
      	         }
      	       }
      	     }
      	     for(int i=0;i<N;i++){
      	        for(int j=0;j<N;j++){
      	          Final[i][j]=(int)1e9;
      	          for(int k=0;k<N;k++){
      	             Final[i][j]=min(Final[i][j],Change[i][k]+Change[j][k]);
      	          } 
      	        }
      	     }
      	     int ans=solve(0,word.size()-1);
      	     return ans >=(int)1e9 ? -1:ans;

	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, string p0, vector <string> p1, bool hasAnswer, int p2) {
	cout << "Test " << testNum << ": [" << "\"" << p0 << "\"" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p1[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	PalindromizationDiv1 *obj;
	int answer;
	obj = new PalindromizationDiv1();
	clock_t startTime = clock();
	answer = obj->getMinimumCost(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	string p0;
	vector <string> p1;
	int p2;
	
	{
	// ----- test 0 -----
	p0 = "racecar";
	p1.clear() /*{}*/;
	p2 = 0;
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	p0 = "topcoder";
	string t1[] = {"erase t 1","erase o 1","erase p 1","erase c 1","erase d 1","erase e 1","erase r 1"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 5;
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	p0 = "topcoder";
	string t1[] = {"erase t 10","erase o 1","erase p 1","erase c 1","erase d 1","erase e 1","erase r 1"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 7;
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	p0 = "caaaaaab";
	string t1[] = {"change b a 100000","change c a 100000","change c d 50000","change b e 50000","erase d 50000","erase e 49999"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 199999;
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	p0 = "moon";
	string t1[] = {"erase o 5","add u 7","change d p 3","change m s 12","change n d 6","change s l 1"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = -1;
	all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
